# extracted directly from a real robot
# refer to: https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_calibration/README.md
kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.2360744983901584
    roll: -0
    pitch: 0
    yaw: -1.595146524881706e-07
  upper_arm:
    x: -2.080344739735765e-05
    y: 0
    z: 0
    roll: 1.569792319469403
    pitch: 0
    yaw: -3.287151297129439e-06
  forearm:
    x: -0.8609499706970828
    y: 0
    z: 0
    roll: 0.0006715421312582943
    pitch: -0.0002805329955904359
    yaw: 1.708600525187942e-06
  wrist_1:
    x: -0.7280871743303204
    y: -0.0001274529879700539
    z: 0.1985643539806042
    roll: 0.000641872359824231
    pitch: -0.002626338738457036
    yaw: 3.87802500407027e-06
  wrist_2:
    x: 2.218941490457152e-05
    y: -0.1591086125268249
    z: 6.081400641198274e-05
    roll: 1.570414109877253
    pitch: 0
    yaw: 5.823190124785993e-07
  wrist_3:
    x: 7.49356980994107e-05
    y: 0.1540713597925837
    z: 0.0002610210680057445
    roll: 1.572490482143644
    pitch: 3.141592653589793
    yaw: 3.14159262415141
  hash: calib_6393829756357316784
  